<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class level_studiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            ['name' => 'SIN ESTUDIOS'],
            ['name' => 'ESTUDIOS PRIMARIOS INCOMPLETOS'],
            ['name' => 'ESTUDIOS PRIMARIOS COMPLETOS'],
            ['name' => 'PROGRAMAS PARA LA FORMACIÓN E INSERCIÓN LABORAL QUE NO PRECISAN DE UNA TITULACIÓN ACADÉMICA DE LA 1ª ETAPA DE SECUNDARIA PARA SU REALIZACIÓN (MÁS DE 300 HORAS)'],
            ['name' => 'PRIMERA ETAPA DE EDUCACIÓN SECUNDARIA SIN TÍTULO DE GRADUADO ESCOLAR O EQUIVALENTE'],
            ['name' => 'PRIMERA ETAPA DE EDUCACIÓN SECUNDARIA CON TÍTULO DE GRADUADO ESCOLAR O EQUIVALENTE'],
            ['name' => 'PROGRAMAS PARA LA FORMACIÓN E INSERCIÓN LABORAL QUE PRECISAN DE UNA TITULACIÓN DE ESTUDIOS SECUNDARIOS DE PRIMERA ETAPA PARA SU REALIZACIÓN (MÁS DE 300 HORAS)'],
            ['name' => 'ENSEÑANZAS DE GRADO MEDIO DE FORMACIÓN PROFESIONAL ESPECÍFICA, ARTES PLÁSTICAS Y DISEÑO Y DEPORTVAS'],
            ['name' => 'ENSEÑANZAS DE GRADO MEDIO DE MÚSICA Y DANZA'],
            ['name' => 'ENSEÑANZAS DE BACHILLERATO'],
            ['name' => 'TÍTULOS PROPIOS DE LAS UNIVERSIDADES Y OTRAS ENSEÑANZAS QUE PRECISAN DEL TÍTULO DE BACHILLER (2 Y MÁS AÑOS)'],
            ['name' => 'ENSEÑANZAS PARA LA FORMACIÓN E INSERCIÓN LABORAL QUE PRECISAN DE UNA TITULACIÓN DE ESTUDIOS SECUNDARIOS DE 2ª ETAPA PARA SU REALIZACIÓN (MÁS DE 300 HORAS)'],
            ['name' => 'ENSEÑANZAS DE GRADO SUPERIOR DE FORMACIÓN PROFESIONAL ESPECÍFICA Y EQUIVALENTES, ARTES PLÁSTICAS Y DISEÑO Y DEPORTIVAS'],
            ['name' => 'ENSEÑANZAS PARA LA FORMACIÓN E INSERCIÓN LABORAL QUE PRECISAN DE UNA FORMACIÓN PROFESIONAL DE GRADO SUPERIOR PARA SU REALIZACIÓN (MÁS DE 300 HORAS)'],
            ['name' => 'ENSEÑANZAS PARA LA FORMACIÓN E INSERCIÓN LABORAL QUE PRECISAN DE UNA FORMACIÓN PROFESIONAL DE GRADO SUPERIOR PARA SU REALIZACIÓN (MÁS DE 300 HORAS)'],
            ['name' => 'ENSEÑANZAS UNIVERSITARIAS DE 1 ER Y 2º CICLO, DE SÓLO SEGUNDO CICLO Y EQUIVALENTES (LICENCIADOS)'],
            ['name' => 'ESTUDIOS OFICIALES DE ESPECIALIZACIÓN PROFESIONAL'],
            ['name' => 'ENSEÑANZAS UNIVERSITARIAS OFICIALES DE MÁSTER'],
            ['name' => 'ENSEÑANZAS UNIVERSITARIAS DE GRADO'],
            ['name' => 'DOCTORADO UNIVERSITARIO'],    
        ];  

         // Insertar los datos en la tabla
         DB::table('level_studies')->insert($datos);
    }
}
