<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class professional_areasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            ['name' => '(ADGD) ADMINISTRACIÓN Y AUDITORÍA'],
            ['name' => '(ADGG) GESTIÓN DE LA INFORMACIÓN Y COMUNICACIÓN'],
            ['name' => '(ADGN) FINANZAS Y SEGUROS'],
            ['name' => '(AFDA) ACTIVIDADES FÍSICO DEPORTIVAS RECREATIVAS'],
            ['name' => '(AFDP) PREVENCIÓN Y RECUPERACIÓN'],
            ['name' => '(AGAJ) JARDINERÍA'],
            ['name' => '(AGAN) GANADERÍA'],
            ['name' => '(AGAR) FORESTAL'],
            ['name' => '(AGAU) AGRICULTURA'],
            ['name' => '(ARGA) ACTIVIDADES Y TÉCNICAS GRÁFICAS ARTÍSTICAS'],
            ['name' => '(ARGC) ENCUADERNACIÓN INDUSTRIAL'],
            ['name' => '(ARGG) DISEÑO GRÁFICO Y MULTIMEDIA'],
            ['name' => '(ARGI) IMPRESIÓN'],
            ['name' => 'DISEÑO GRÁFICO Y MULTIMEDIA'],
            ['name' => '(ARGN) EDICIÓN'],
            ['name' => '(ARGP) PREIMPRESIÓN'],
            ['name' => '(ARGT) TRANSFORMACION Y CONVERSIÓN EN INDUSTRIAS GRÁFICAS'],
            ['name' => '(ARTA) ARTESANÍA TRADICIONAL'],
            ['name' => '(ARTB) JOYERIA Y ORFEBRERIA'],
            ['name' => '(ARTG) FABRICACIÓN Y MANTENIMIENTO DE INSTRUMENTOS MUSICALES'],
            ['name' => '(ARTN) VIDRIO Y CERÁMICA ARTESANAL'],
            ['name' => '(ARTR) RECUPERACIÓN, REPARACIÓN Y MANTENIMIENTO ARTÍSTICOS'],
            ['name' => '(ARTU) ARTES ESCÉNICAS'],
            ['name' => '(COML) LOGÍSTICA COMERCIAL Y GESTIÓN DEL TRANSPORTE'],
            ['name' => '(COMM) MARKETING Y RELACIONES PÚBLICAS'],
            ['name' => '(COMT) COMPRAVENTA'],
            ['name' => '(ELEE) INSTALACIONES ELÉCTRICAS'],
            ['name' => '(ELEQ) EQUIPOS ELECTRÓNICOS'],
            ['name' => '(ENAA) AGUA'],
            ['name' => '(ENAE) ENERGÍAS RENOVABLES'],
            ['name' => '(ENAL) ENERGÍA ELÉCTRICA'],
            ['name' => '(ENAS) GAS'],
            ['name' => '(EOCB) ALBAÑILERÍA Y ACABADOS'],
            ['name' => '(EOEC) ESTRUCTURAS'],
            ['name' => '(EOCJ) COLOCACIÓN Y MONTAJE'],
            ['name' => '(EOCO) PROYECTOS Y SEGUIMIENTO DE OBRAS'],
            ['name' => '(EOCQ) MAQUINARIA DE CONSTRUCCIÓN'],
            ['name' => '(FCOA) ASPECTOS MEDIOAMBIENTALES'],
            ['name' => '(FCOE) LENGUAS EXTRANJERAS'],
            ['name' => '(FCOL) LENGUAS Y DIALECTOS ESPAÑOLES'],
            ['name' => '(FCOV) COMPETENCIAS CLAVE'],
            ['name' => '(FMEC) CONSTRUCCIONES METÁLICAS'],
            ['name' => '(FMEF) FUNDICIÓN'],
            ['name' => '(FMEH) OPERACIONES MECÁNICAS'],
            ['name' => '(FMEM) PRODUCCIÓN MECÁNICA'],
            ['name' => '(HOTA) ALOJAMIENTO'],
            ['name' => '(HOTJ) JUEGOS DE AZAR'],
            ['name' => '(HOTR) TURISMO'],
            ['name' => '(HOTT) AGROTURISMO'],
            ['name' => '(IEXD) PIEDRA NATURAL'],
            ['name' => '(IEXM) MINERÍA'],
            ['name' => '(IFCD) DESARROLLO'],
            ['name' => '(IFCM) COMUNICACIONES'],
            ['name' => '(IFCT) SISTEMAS Y TELEMÁTICA'],
            ['name' => '(IMAI) MONTAJE Y MANTENIMIENTO DE INSTALACIONES'],
            ['name' => '(IMAQ) MAQUINARIA Y EQUIPO INDUSTRIAL'],
            ['name' => '(IMAR) FRÍO Y CLIMATIZACIÓN'],
            ['name' => '(IMPE) ESTÉTICA'],
            ['name' => '(IMPQ) PELUQUERÍA'],
            ['name' => '(IMSE) ESPECTÁCULOS EN VIVO'],
            ['name' => '(IMST) PRODUCCIONES FOTOGRÁFICAS'],
            ['name' => '(IMSV) PRODUCCIÓN AUDIOVISUAL'],
            ['name' => '(INAD) ALIMENTOS DIVERSOS'],
            ['name' => '(INAE) LÁCTEOS'],
            ['name' => '(INAF) PANADERÍA, PASTELERÍA, CONFITERÍA Y MOLINERÍA'],
            ['name' => '(INAH) BEBIDAS'],
            ['name' => '(INAI) CÁRNICAS'],
            ['name' => '(INAJ) PRODUCTOS DE LA PESCA'],
            ['name' => '(INAK) ACEITES Y GRASAS'],
            ['name' => '(INAV) CONSERVAS VEGETALES'],
            ['name' => '(MAMA) TRANSFORMACIÓN MADERA Y CORCHO'],
            ['name' => '(MAMB) INSTALACIÓN Y AMUEBLAMIENTO'],
            ['name' => '(MAMD) PRODUCCION CARPINTERÍA Y MUEBLE'],
            ['name' => '(MAPB) BUCEO'],
            ['name' => '(MAPN) PESCA Y NAVEGACIÓN'],
            ['name' => '(MAPU) ACUICULTURA'],
            ['name' => '(QUIA) ANÁLISIS Y CONTROL'],
            ['name' => '(QUIE) PROCESO QUÍMICO'],
            ['name' => '(QUIM) FARMAQUÍMICA'],
            ['name' => '(QUIO) PASTA, PAPEL Y CARTÓN'],
            ['name' => '(QUIT) TRANSFORMACIÓN DE POLÍMEROS'],
            ['name' => '(SANP) SERVICIOS Y PRODUCTOS SANITARIOS'],
            ['name' => '(SANS) SOPORTE Y AYUDA AL DIAGNÓSTICO'],
            ['name' => '(SANT) ATENCIÓN SANITARIA'],
            ['name' => '(SEAD) SEGURIDAD Y PREVENCIÓN'],
            ['name' => '(SEAG) GESTIÓN AMBIENTAL'],
            ['name' => '(SSCB) ACTIVIDADES CULTURALES RECREATIVAS'],
            ['name' => '(SSCE) FORMACIÓN Y EDUCACIÓN'],
            ['name' => '(SSCG) ATENCIÓN SOCIAL'],
            ['name' => '(SSCI) SERVICIOS AL CONSUMIDOR'],
            ['name' => '(TCPC) CALZADO'],
            ['name' => '(TCPF) CONFECCIÓN EN TEXTIL Y PIEL'],
            ['name' => '(TCPN) ENNOBLECIMIENTO DE MATERIAS TEXTILES Y PIELES'],
            ['name' => '(TCPP) PRODUCCIÓN DE HILOS Y TEJIDOS'],
            ['name' => '(TMVB) FERROCARRIL Y CABLE'],
            ['name' => '(TMVG) ELECTROMECÁNICA DE VEHÍCULOS'],
            ['name' => '(TMVI) CONDUCCION DE VEHÍCULOS POR CARRETERA'],
            ['name' => '(TMVL) CARROCERÍA DE VEHÍCULOS'],
            ['name' => '(TMVO) AERONÁUTICA'],
            ['name' => '(TMVU) NÁUTICA'],
            ['name' => '(VICF) FABRICACIÓN CERÁMICA'],
            ['name' => '(VICI) VIDRIO INDUSTRIAL'],
            ['name' => '(FCOI) INFORMÁTICA COMPLEMENTARIA'],
            ['name' => '(FCOM) MANIPULACIÓN ALIMENTARIA'],
            ['name' => '(FCOO) ORIENTACIÓN LABORAL'],
            ['name' => '(FCOS) SEGURIDAD Y SALUD LABORAL'],
            ['name' => '(ELEM) MÁQUINAS ELECTROMECÁNICAS'],
            ['name' => '(ELES) INSTALACIONES DE TELECOMUNICACIÓN'],
            ['name' => '(ENAC) EFICIENCIA ENERGÉTICA'],
            ['name' => '(FMEA) CONSTRUCCIONES AREONÁUTICAS'],
            ['name' => '(HOTR) RESTAURACIÓN'],
        ];
         
        
         // Insertar los datos en la tabla
         DB::table('professional_areas')->insert($datos);
    }
    }

